### ISSUE TITLE
Further seismiQB improvements

### ISSUE THREAD

**Issue by SergeyTsimfer** [gazprom-neft/seismiqb#120]
- [ ] auto-build documentation
- [x] re-write the title page
- [x] make a separate `Field` class to combine geometry and labeled structures
- [x] remove unstructured geometry wherever possible
- [x] make more tests and benchmarks on synthetic geometry

**Comment by SergeyTsimfer** [comment]
Refactor `show_slide`: currently, we 4 different implementations, and that is 3 too many

**Comment by SergeyTsimfer** [comment]
Add storage format for Horizon: if there is a `path + '.qb'` file, then use it to load data instead of re-parsing the `.csv`

**Comment by SergeyTsimfer** [comment]
Benchmark `Horizon.*_merge` and speed up, if possible

**Comment by cdtn** [comment]
Add `CacheMixin` tests

**Comment by SergeyTsimfer** [comment]
Rework `field` attribute of the `SeismicGeometry`: make it a reference to a containing `Field`

**Comment by SergeyTsimfer** [comment]
By the current date, everything but the very last comment is implemented
Good job team!
