### ISSUE TITLE
python environment issues

### ISSUE THREAD

**Issue by MikhailShi** [gazprom-neft/seismiqb#15]
Could you please kindly provide full description of requirements:
`pip freeze > requirements.txt`
 as well as confirm the version of python==3.5 for running this repository. Thanks in advance.

**Comment by SergeyTsimfer** [comment]
Hello!
Here is the file with requirements:
[requirements.txt](https://github.com/gazprom-neft/seismiqb/files/4600747/requirements.txt)

Regarding your other question: yes, most parts of the framework would work with python 3.5, yet it would be better to use python 3.6 due to f-strings.

**Comment by MikhailShi** [comment]
Thanks, Sergey! That helps a lot.
