### ISSUE TITLE
Further seismiQB improvements 

### ISSUE THREAD

**Issue by SergeyTsimfer** [gazprom-neft/seismiqb#17]
This is the list of things to do in order to make the framework better again:

- Rethink `Horizon` storage location: it would be beneficial to attach them to corresponding `Geometry`, without using additional structure in `Dataset`. It would (hopefully) also make code much cleaner

- Rethink `Sampler` and also make it a property of `Geometry`: also, there is pretty much no need to use [0; 1] sampling anymore

- Add more methods to `UnstructuredHorizon` and make it compatible with 1D index (for 2D seismic)

- Make `Geobody` class work with seismic facies
 
- `metrics.py` currently experiencing a lot of code duplication; also, maybe it would be better to get rid of `evaluate` and use methods directly: that would require additional `plottable` decorator

**Comment by SergeyTsimfer** [comment]
Change `locations` in case of HDF5 file to simple slices:

- split `CropBatch` into separate classes for structured and unstructured geometry, with difference being in how `locations` are working: for the unstructured case, that is a set of trace identifiers, for HDF5 we can use a simple 3D slice

- change `locations` processing in `Horizon` and `SeismicGeometryHDF5`

**Comment by cdtn** [comment]
Allow passing `'all'` to `ilines_range` and `xlines_range` arguments of `SeismicCubeset.make_grid`.

**Comment by SergeyTsimfer** [comment]
add demo notebook for metrics

**Comment by roman-kh** [comment]
> Allow passing `'all'` to `ilines_range` and `xlines_range` arguments of `SeismicCubeset.make_grid`.

remove `_range` for brevity and simplicity

**Comment by SergeyTsimfer** [comment]
Add `GPUCropBatch`

**Comment by cdtn** [comment]
> `SeismicCubeset.load` implements outdated (in many ways) logic and should be updated to the current quality standards.

**Comment by SergeyTsimfer** [comment]
- project: clean-up
- static typing for Horizon and Geometry
- use separate processes for `inference` in `Controllers`

**Comment by SergeyTsimfer** [comment]
- Add `df_transform` to horizon loading

- auto-infer cube step along `INLINE_3D` and  `CROSSLINE_3D` axis

**Comment by cdtn** [comment]
Upgrade `SeismicCubeset.__getitem__` to allow `cubeset[idx]` calls.

**Comment by AlexeyKozhevin** [comment]
Add custom headers creation to `make_sgy`
