### ISSUE TITLE
ImportError: cannot import name 'SeismicGeometry' from 'seismiqb'

### ISSUE THREAD

**Issue by David-Thul** [gazprom-neft/seismiqb#228]
Hi seismiQB Team,

On cloning the repo, creating a fresh environment and pip installing seismiqb per the instructions the environment builds fine and everything installs fine. 

Trying to use the 01_Geometry_part1.ipynb on running the import cell I am faced with the following error:

ImportError                               Traceback (most recent call last)
Cell In [4], line 12
      9 warnings.filterwarnings('ignore')
     11 sys.path.append('..')
---> 12 from seismiqb import SeismicGeometry
     13 from seismiqb import plot_image
     15 FIGURE_SCALE = 1.5

ImportError: cannot import name 'SeismicGeometry' from 'seismiqb'

Not sure if I am missing something simple here in my setup and install. Thanks.

System Details:
Windows 11
Python 3.10.6

**Comment by SergeyTsimfer** [comment]
Hey

It looks like you've cloned our tutorials right at the moment of their refactoring (and some renamings). Now everything should be ok 😄 

Feel free to re-open the issue if you have any other questions
